version: "2.1"

services:
  backend:
    image: docksal/node:12  # Use a suitable Node.js version
    volumes:
      - project_root:/var/www
    working_dir: /var/www/backend
    environment:
      - NODE_ENV=development
    command: ["npm", "start"]
    depends_on:
      - mongo
    ports:
      - "5000:5000"  # Assuming your backend runs on port 3001

  frontend:
    image: docksal/node:12  # Use a suitable Node.js version
    volumes:
      - project_root:/var/www
    working_dir: /var/www/frontend
    environment:
      - NODE_ENV=development
    command: ["npm", "start"]
    depends_on:
      - backend
    ports:
      - "3000:3000"  # Assuming your frontend runs on port 3000

  mongo:
    image: mongo:latest
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"

volumes:
  mongo_data:
